ALTER TABLE users ADD COLUMN is_expert BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN bio VARCHAR(500);
ALTER TABLE users ADD COLUMN professional_title VARCHAR(100);
ALTER TABLE users ADD COLUMN organization VARCHAR(100);
ALTER TABLE users ADD COLUMN years_experience INTEGER;
ALTER TABLE users ADD COLUMN specializations VARCHAR(255);
ALTER TABLE users ADD COLUMN portfolio_url VARCHAR(255);
